version: '3'
services:
  customer-service:
    image: ebayego/customer-service:latest
    build: ./customer-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  inventory-service:
    image: ebayego/inventory-service:latest
    build: ./inventory-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  order-service:
    image: ebayego/order-service:latest
    build: ./order-service
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  product-service:
    image: ebayego/product-service:latest
    build: ./product-service
    ports:
      - "8084:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
