services:
  customer-service:
    container_name: customer-service
    build: ./customer-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  order-service:
    container_name: order-service
    build: ./order-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  product-service:
    container_name: product-service
    build: ./product-service
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
